from app import db

class BusinessRequest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(64), index=True)
    last_name = db.Column(db.String(64), index=True)
    email = db.Column(db.String(120), index=True)
    address_of_car = db.Column(db.String(120), index=True)
    waterless_wash = db.Column(db.Boolean, index=True)
    interior_clean = db.Column(db.Boolean, index=True)
    full_detail = db.Column(db.Boolean, index=True)
    oil_change = db.Column(db.Boolean, index=True)
    tire_rotation = db.Column(db.Boolean, index=True)
    brakes = db.Column(db.Boolean, index=True)
    car_to_dealership = db.Column(db.Boolean, index=True)
    state_inspection = db.Column(db.Boolean, index=True)
    wiper_replacement = db.Column(db.Boolean, index=True)
    cabin_air_filter = db.Column(db.Boolean, index=True)
    engine_air_filter = db.Column(db.Boolean, index=True)
    year = db.Column(db.Integer, index=True)
    make = db.Column(db.String(64), index=True)
    model = db.Column(db.String(64), index=True)
    engine_type = db.Column(db.String(64), index=True)
    license_plate = db.Column(db.String(64), index=True)
    color = db.Column(db.String(64), index=True)
    misc = db.Column(db.String(512), index=True)

    def __repr__(self):
        return '<User %r>' % (self.first_name)

class RegularRequest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(64), index=True)
    last_name = db.Column(db.String(64), index=True)
    email = db.Column(db.String(120), index=True)
    personal_address = db.Column(db.String(120), index=True)
    personal_driveway = db.Column(db.Boolean, index=True)
    street = db.Column(db.Boolean, index=True)
    garage_closed = db.Column(db.Boolean, index=True)
    garage_open = db.Column(db.Boolean, index=True)
    lot_closed = db.Column(db.Boolean, index=True)
    lot_open = db.Column(db.Boolean, index=True)
    address_of_car = db.Column(db.String(120), index=True)
    waterless_wash = db.Column(db.Boolean, index=True)
    interior_clean = db.Column(db.Boolean, index=True)
    full_detail = db.Column(db.Boolean, index=True)
    oil_change = db.Column(db.Boolean, index=True)
    tire_rotation = db.Column(db.Boolean, index=True)
    brakes = db.Column(db.Boolean, index=True)
    car_to_dealership = db.Column(db.Boolean, index=True)
    state_inspection = db.Column(db.Boolean, index=True)
    wiper_replacement = db.Column(db.Boolean, index=True)
    cabin_air_filter = db.Column(db.Boolean, index=True)
    engine_air_filter = db.Column(db.Boolean, index=True)
    year = db.Column(db.Integer, index=True)
    make = db.Column(db.String(64), index=True)
    model = db.Column(db.String(64), index=True)
    engine_type = db.Column(db.String(64), index=True)
    license_plate = db.Column(db.String(64), index=True)
    color = db.Column(db.String(64), index=True)
    misc = db.Column(db.String(512), index=True)

    def __repr__(self):
        return '<User %r>' % (self.first_name)
